#!/bin/bash

bucket="ezbds-bin"
stack_id="webhook-explorer1"

echo "Packaging..."
if ! docker-compose run --rm aws cloudformation package --template-file template.yml --output-template-file built-template.yml --s3-bucket ${bucket} ; then
  echo "Failed to package"
  exit 2
fi

echo "Deploying..."
if ! docker-compose run --rm aws cloudformation deploy --template-file built-template.yml --stack-name "${stack_id}" --parameter-overrides "WebhookDomainName=api.easybetes.com" "WebhookHostedZoneId=Z3M2WNLI9UC7O9" "WebhookExplorerAuthDomainName=auth-webhook-explorer.easybetes.com" "WebhookExplorerDomainName=webhook-explorer.easybetes.com" "WebhookExplorerHostedZoneId=Z3M2WNLI9UC7O9" "AdminEmailAddress=adam.g.berger@gmail.com" --capabilities CAPABILITY_IAM; then
  echo "Failed to deploy"
  exit 2
fi
