#!/bin/bash

bucket="ezbds-bin"
stack_id="webhook-explorer"

echo "Building..."
if ! docker-compose run --rm --service-ports lein with-profile release run -m shadow.cljs.devtools.cli --npm release :lambda ; then
  echo "Failed to build"
  exit 2
fi

echo "Packaging..."
if ! docker-compose run --rm --entrypoint /project/scripts/package-in-docker aws "${bucket}" ; then
  echo "Failed to package"
  exit 2
fi

echo "Deploying..."
if ! docker-compose run --rm aws cloudformation deploy --template-file /project/built-template.yml --stack-name "${stack_id}" --parameter-overrides "WebhookDomainName=api.easybetes.com" "WebhookHostedZoneId=Z3M2WNLI9UC7O9" "WebhookExplorerAuthDomainName=auth-webhook-explorer.easybetes.com" "WebhookExplorerDomainName=webhook-explorer.easybetes.com" "WebhookExplorerHostedZoneId=Z3M2WNLI9UC7O9" "AdminEmailAddress=adam.g.berger@gmail.com" --capabilities CAPABILITY_IAM; then
  echo "Failed to deploy"
  exit 2
fi
