version: '2'
services:
  aws:
    image: mesosphere/aws-cli:1.14.5
    volumes:
     - ".:/project"
     - "${AWS_CONFIG_DIR}:/root/.aws"
    network_mode: "bridge"
    working_dir: "/project/lambdas"
  app:
    image: aws-sam:0.6.0
    environment:
     - "DOCKER_HOST=tcp://host.docker.internal:2375"
    ports:
     - "3000:3000"
    volumes:
     - ".:/var/opt"
     - "${AWS_CONFIG_DIR}:/root/.aws"
    network_mode: "bridge"
  lein:
    image: webhook-explorer/lein
    build:
      context: .
      dockerfile: lein.dockerfile
    volumes:
      - ".:/usr/src/app"
      - "${M2_DIR}:/root/.m2"
      - "./.aws:/root/.aws:ro"
    entrypoint: ["lein"]
    working_dir: "/usr/src/app"
    ports:
      - "9000:9000"
      - "9500:9500"
      - "9630:9630"
      - "9700:9700"
  npm:
    image: webhook-explorer/lein
    build:
      context: .
      dockerfile: lein.dockerfile
    volumes:
      - ".:/usr/src/app"
      - "${M2_DIR}:/root/.m2"
      - "./.aws:/root/.aws:ro"
    entrypoint: ["npm"]
    working_dir: "/usr/src/app"
  lambda-npm:
    image: webhook-explorer/lein
    build:
      context: .
      dockerfile: lein.dockerfile
    volumes:
      - ".:/usr/src/app"
      - "${M2_DIR}:/root/.m2"
      - "./.aws:/root/.aws:ro"
    entrypoint: ["npm"]
    working_dir: "/usr/src/app/lambdas"
