AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Webhook Explorer
Parameters:
  WebhookDomainName:
    Type: String
  WebhookHostedZoneId:
    Type: AWS::Route53::HostedZone::Id
  WebhookExplorerAuthDomainName:
    Type: String
  WebhookExplorerDomainName:
    Type: String
  WebhookExplorerHostedZoneId:
    Type: AWS::Route53::HostedZone::Id
Resources:
  WebhookApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        swagger: "2.0"
        info:
          version: "1.0"
          title: webhook-api
        basePath: "/"
        schemes:
          - "http"
          - "https"
        paths:
          /{proxy+}:
            x-amazon-apigateway-any-method:
              produces:
                - "application/json"
              parameters:
                - name: "proxy"
                  in: "path"
                  required: true
                  type: "string"
              responses: {}
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebhookHandler.Arn}/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"
  WebhookHandler:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      Handler: src/webhook-handler.handler
      MemorySize: 512
      Timeout: 10
      AutoPublishAlias: live
      Events:
        WebhookApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: "*"
            RestApiId: !Ref WebhookApi
      Environment:
        Variables:
          BUCKET_NAME: !Ref WebhookRequestBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref WebhookRequestBucket
  WebhookHandlerPermissionFix:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebhookHandler
      Principal: apigateway.amazonaws.com
  CustomCertificateCreator:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      Handler: src/custom-certificate-creator.handler
      MemorySize: 512
      Timeout: 600
      AutoPublishAlias: live
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - acm:DescribeCertificate
              - acm:DeleteCertificate
              - acm:RequestCertificate
            Resource: "*"
        - Statement:
          - Effect: Allow
            Action:
              - route53:*
            Resource: !Sub "arn:${AWS::Partition}:route53:::hostedzone/${WebhookHostedZoneId}"
  Certificate:
    Type: 'Custom::CertificateCreator'
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt CustomCertificateCreator.Arn
      HostedZoneId: !Ref WebhookHostedZoneId
      DomainName: !Ref WebhookDomainName
  WebhookDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref WebhookDomainName
      RegionalCertificateArn: !Ref Certificate
      EndpointConfiguration:
        Types:
          - "REGIONAL"
  WebhookDomainMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref WebhookDomain
      RestApiId: !Ref WebhookApi
      Stage: prod
  WebhookRequestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-${AWS::AccountId}-webhook-reqs"
  WebhookDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties: 
      Comment: "DNS for Webhook API"
      HostedZoneId: !Ref WebhookHostedZoneId
      RecordSets: 
        - Name: !Ref WebhookDomain
          Type: "A"
          AliasTarget:
            DNSName: !GetAtt WebhookDomain.RegionalDomainName
            HostedZoneId: !GetAtt WebhookDomain.RegionalHostedZoneId
  WebhookExplorerUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
        InviteMessageTemplate:
          EmailSubject: "You're invited to Webhook Explorer"
          EmailMessage: "Welcome to Webhook Explorer.  You can log in with username \"{username}\"  and password \"{####}\"."
      AliasAttributes:
        - email
        - preferred_username
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
        ReplyToEmailAddress: "adam.g.berger@gmail.com"
      Schema:
        - AttributeDataType: String
          Name: tenant_role
      UserPoolName: !Sub "${AWS::StackName}-user-pool"
  WebhookExplorerApp:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: WebhookExplorer
      UserPoolId: !Ref WebhookExplorerUserPool
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
      AllowedOAuthFlowsUserPoolClient: true
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - !Sub "https://${WebhookExplorerDomainName}/"
  WebhookExplorerCertificate:
    Type: 'Custom::CertificateCreator'
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt CustomCertificateCreator.Arn
      HostedZoneId: !Ref WebhookExplorerHostedZoneId
      DomainName: !Ref WebhookExplorerAuthDomainName
  CustomCognitoDomainCreator:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      Handler: src/custom-cognito-domain.handler
      MemorySize: 512
      Timeout: 600
      AutoPublishAlias: live
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - cognito-idp:DescribeUserPoolDomain
              - cognito-idp:DeleteUserPoolDomain
              - cognito-idp:CreateUserPoolDomain
            Resource: !GetAtt WebhookExplorerUserPool.Arn
          - Effect: Allow
            Action:
              - cloudfront:UpdateDistribution
            Resource: "*"
  CustomCognitoDomain:
    Type: 'Custom::CustomCognitoDomainCreator'
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt CustomCognitoDomainCreator.Arn
      UserPoolId: !Ref WebhookExplorerUserPool
      Domain: !Ref WebhookExplorerAuthDomainName
      CertificateArn: !Ref WebhookExplorerCertificate
  CognitoDomainDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties: 
      Comment: "DNS for Cognito Auth"
      HostedZoneId: !Ref WebhookExplorerHostedZoneId
      RecordSets: 
        - Name: !Ref WebhookExplorerAuthDomainName
          Type: "A"
          AliasTarget:
            DNSName: !Ref CustomCognitoDomain
            HostedZoneId: Z2FDTNDATAQYW2
